name: 'redocly open api cli'
description: 'redocly open api cli as actions'
author: 'Mohammad Saif Husain'
inputs:
  cmd:
    description: 'redocly cli command to run'
    required: true 
  open-api-spec-path:
    description: 'path to find open api spec'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
    - ${{ inputs.open-api-spec-path }}
